language: rust
before_install:
  - sudo apt-get install -y nettle-bin nettle-dev
env:
    #  - CRATE="blockchain"
  - CRATE="presentations/concurrency/"
  - CRATE="presentations/pattern_matching/"
script:
  - cd $CRATE
  - cargo build
  - cargo test -v
  - cargo doc
