language: rust
#before_install:
#    - git clone https://git.lysator.liu.se/nettle/nettle
#    - cd nettle
#    - ./.bootstrap
#    - ./configure
#    - make
#    - sudo make install
#    - cd ..
env:
  - CRATE="blockchain"
script:
  - cd $CRATE
  - cargo build
  - cargo test -v
  - cargo doc --no-deps --document-private-items
