language: rust
before_install:
    git clone https://git.lysator.liu.se/nettle/nettle
    cd nettle
    ./.bootstrap
    ./configure
    make
    sudo make install
env:
  - CRATE="blockchain"
  - CRATE="presentations/concurrency/"
  - CRATE="presentations/pattern_matching/"
script:
  - cd $CRATE
  - cargo build
  - cargo test -v
  - cargo doc
