[package]
name = "transactions"
version = "0.1.0"
authors = ["Chuggi, Chuggo, Chuggu"]
workspace = ".."

[dependencies]
serde = "1.0.93"
serde_json = "1.0.39"
serde_derive = "1.0.94"
chrono = "0.4.7"
