[package]
name = "blockchain"
version = "0.1.0"
authors = ["Fabian Klopfer <fabian.klopfer@ieee.org>", "Felix Mayer", "Stephan Perren"]
edition = "2018"

[dependencies]
time = "0.1.42"
chrono = "0.4.6"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
serde_bytes = "0.11.1"
crypto-hash = ""
pgp = "0.2.1"
tokio = "0.1.21"
hex = "0.3.2"
